### ISSUE TITLE
Deserializing JSOG to abstract type

### ISSUE THREAD

**Issue by creativeux** [jsog/jsog-jackson#10]
JSOG has been a life saver for our project backed by Neo4j for eliminating infinite recursion, but we're running into trouble with a Java -> Java transfer over REST between microservices.  Our model follows an Interface -> abstract Class -> Impl class structure, and our JSON needs to be deserialized to an implementing class of the specified abstract class.  I am using JSOGGenerator alongside JsonTypeInfo and the order of parsing seems to be backwards.  Jackson is trying to deserialize the JSON object before JSOG is able to point to the existing ref.

I've put together a unit test that shows the failure.  It's entirely possible that I'm just using the annotations incorrectly, but I thought I'd post it here for review.  Thanks in advance!

``` java
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.voodoodyne.jackson.jsog.JSOGGenerator;
import org.junit.Test;

/**
 * Created by aaronstone on 1/8/16.
 */
public class JSOGDeserializeAbstractTest {

    /**
     * the key of the property that holds the ref
     */
    public static final String REF_KEY = "@ref";

    /**
     * Reference for string matching.
     */
    private static final String TEST_USER = "TEST_USER";

    /**
     * JSON input
     */
    private static final String USER_JSOG = "{\"@id\":\"1\",\"type\":\"" + TEST_USER + "\",\"user\":{\"@ref\":\"1\"}}";

    ObjectMapper mapper = new ObjectMapper();

    /**
     * Abstract base class.
     */
    @JsonIdentityInfo(generator = JSOGGenerator.class)
    @JsonTypeInfo(
            use = JsonTypeInfo.Id.NAME,
            include = JsonTypeInfo.As.PROPERTY,
            property = "type",
            visible = true)
    @JsonSubTypes({
            @JsonSubTypes.Type(value = UserImpl.class, name = TEST_USER)
    })
    public static abstract class User {

        public String type;
        public User user;

        public User() {
            this.type = getUserType();
        }

        public abstract String getUserType();

    }

    /**
     * Implementing class that should be instantiated via the "type" field.
     */
    public static class UserImpl extends User {

        public UserImpl() {
            super();
        }

        public String getUserType() {
            return TEST_USER;
        }
    }

    @Test
    public void testAbstractDeserialization() throws Exception {
        User user = mapper.readValue(USER_JSOG, User.class);
        assert user.type.equals(TEST_USER);
    }
}
```

This test is producing the following error:

```
com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property 'type' that is to contain type id  (for class com.gci.jsog.test.JSOGDeserializeAbstractTest$User)
 at [Source: {"@id":"1","type":"TEST_USER","user":{"@ref":"1"}}; line: 1, column: 49] (through reference chain: com.gci.jsog.test.UserImpl["user"])
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
    at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:946)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:149)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:101)
    at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:518)
    at com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty.deserializeSetAndReturn(ObjectIdReferenceProperty.java:75)
    at com.fasterxml.jackson.databind.deser.impl.ObjectIdReferenceProperty.deserializeAndSet(ObjectIdReferenceProperty.java:68)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:339)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithObjectId(BeanDeserializerBase.java:1071)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:164)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:136)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:122)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:93)
    at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
    at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:42)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3736)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2726)
    at com.gci.jsog.test.JSOGDeserializeAbstractTest.testAbstractDeserialization(JSOGDeserializeAbstractTest.java:75)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by creativeux** [comment]
Immediately after hitting "submit" on this issue, I found these...  This issue may be a duplicate.

https://github.com/jsog/jsog-jackson/pull/8
https://github.com/FasterXML/jackson-databind/issues/1032

**Comment by obozek** [comment]
This is fixed in Jackson 2.7.0.RC2 I tested it with Jackson 2.7.2 and it works now. I' superhapppy!

**Comment by stickfigure** [comment]
Great!

**Comment by creativeux** [comment]
Thank you!
