### ISSUE TITLE
JSOG doesn't handle circular references correctly

### ISSUE THREAD

**Issue by doraeimo** [jsog/jsog-jackson#26]
I'm serializing and deserializing a list including two objects, with circular references there.

```java
//Using latest version for the dependencies
//jackson.version = 2.13.1
//jackson-jsog = 1.1.2

    @NoArgsConstructor
    @JsonIdentityInfo(generator = JSOGGenerator.class)
    public static class Outer {
        @Setter
        @Getter
        private Inner inner;
    }

    @NoArgsConstructor
    @JsonIdentityInfo(generator = JSOGGenerator.class)
    public static class Inner {

        @Getter
        private Outer outer;

        public Inner(Outer outer) {
            this.outer = outer;
            outer.setInner(this);
        }
    }

    public static void main(String[] args) throws Exception {
        // There are circular references between Outer and Inner
        Outer outer = new Outer();
        Inner inner = new Inner(outer);
        // Turn on type info
        PolymorphicTypeValidator ptv = BasicPolymorphicTypeValidator.builder().allowIfSubType(Object.class).build();
        ObjectMapper mapper = new ObjectMapper()
                .activateDefaultTyping(ptv, ObjectMapper.DefaultTyping.EVERYTHING,
                        JsonTypeInfo.As.PROPERTY);

        List<Object> source = Lists.newArrayList(outer, inner);
        String json = mapper.writeValueAsString(source);
        System.out.println(json);
        //This is the json serialized by JSOGGenerator, which does make sense
        //See below
        List<Object> target = mapper.readerForListOf(Object.class).readValue(json);
        //However, I got an InvalidTypeIdException while deserializing
        //Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class com.voodoodyne.jackson.jsog.JSOGRef]: missing type id property '@class'

    }


```

This is the json serialized by JSOGGenerator, which does make sense.

```json

[
    "java.util.ArrayList",
    [
        {
            "@class": "com.foo.bar.SomeTest$Outer",
            "@id": "1",
            "inner":
            {
                "@class": "com.foo.bar.SomeTest$Inner",
                "@id": "2",
                "outer":
                {
                    "@ref": "1"
                }
            }
        },
        {
            "@ref": "2"
        }
    ]
]

```

However, I got an `InvalidTypeIdException` while deserializing.
And I found the property "@id" is not handled correctly.

See `ObjectIdValueProperty._valueDeserializer._baseType`, which type is `JSOGRef` and it can not parse "1"(String) as object id value.

**Comment by nsoft** [comment]
This appears to only be an issue with default typing. 
If that configuration is removed, the above example works just fine, and it also works just fine with

````java
  @JsonTypeInfo(use = JsonTypeInfo.Id.MINIMAL_CLASS, include = JsonTypeInfo.As.PROPERTY, property = "@class")
````

I think the real problem here stems from things like: 
````
        {
            "@ref": "2"
        }
````
not having an `@class` in the json. Maybe they are processed in the wrong order (need to be replaced with the ref before validation of `@class` occurs?)

**Comment by nsoft** [comment]
In fact this has nothing to do with circularity... it's the list that's causing a problem. I get the same exception from:

````java
package com;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.jsontype.BasicPolymorphicTypeValidator;
import com.fasterxml.jackson.databind.jsontype.PolymorphicTypeValidator;
import com.google.common.collect.Lists;
import com.voodoodyne.jackson.jsog.JSOGGenerator;

public class JsogTest {
  @JsonIdentityInfo(generator = JSOGGenerator.class)
  public static class Foo {
    public String mystring = "foo";
  }

  @JsonIdentityInfo(generator = JSOGGenerator.class)
  public static class Bar {
    public String mystring = "bar";
  }

  public static void main(String[] args) throws Exception {
    Foo outer = new Foo();
    Bar inner = new Bar();
    PolymorphicTypeValidator ptv = BasicPolymorphicTypeValidator.builder().allowIfSubType(Object.class).build();
    ObjectMapper mapper = new ObjectMapper()
        .activateDefaultTyping(ptv, ObjectMapper.DefaultTyping.EVERYTHING, JsonTypeInfo.As.PROPERTY);
    List<Object> source = Lists.newArrayList(outer, inner);
    String json = mapper.writeValueAsString(source);
    System.out.println(json);
    mapper.readerForListOf(Object.class).readValue(json); // boom!
  }

}
````

The JSON printed  is:
````
[
  "java.util.ArrayList",
  [
    {
      "@class": "com.JsogTest$Foo",
      "@id": "1",
      "mystring": "foo"
    },
    {
      "@class": "com.JsogTest$Bar",
      "@id": "2",
      "mystring": "bar"
    }
  ]
]
````

(only without newlines)

````
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve subtype of [simple type, class com.voodoodyne.jackson.jsog.JSOGRef]: missing type id property '@class'
 at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 60] (through reference chain: java.util.ArrayList[0]->com.JsogTest$Foo["@id"])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:43)
	at com.fasterxml.jackson.databind.DeserializationContext.missingTypeIdException(DeserializationContext.java:2078)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingTypeId(DeserializationContext.java:1649)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleMissingTypeId(TypeDeserializerBase.java:308)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:210)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:121)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:239)
	at com.fasterxml.jackson.databind.JsonDeserializer.deserializeWithType(JsonDeserializer.java:158)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.impl.ObjectIdValueProperty.deserializeSetAndReturn(ObjectIdValueProperty.java:99)
	at com.fasterxml.jackson.databind.deser.impl.ObjectIdValueProperty.deserializeAndSet(ObjectIdValueProperty.java:83)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:392)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithObjectId(BeanDeserializerBase.java:1463)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:210)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:179)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:169)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:135)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:239)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializerNR.deserializeWithType(UntypedObjectDeserializerNR.java:111)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeNoNullChecks(CollectionDeserializer.java:503)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:358)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:29)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:122)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:55)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserializeWithType(CollectionDeserializer.java:284)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2130)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1565)
	at com.JsogTest.main(JsogTest.java:36)
````

**Comment by nsoft** [comment]
Another observation: `ObjectMapper.DefaultTyping.JAVA_LANG_OBJECT` works just fine in the original example if you provide a default constructor for `Inner` (and remove the lombok annotations). Putting the list as a field of an additional object seems to allow it to work with `OBJECT_AND_NON_CONCRETE`

**Comment by nsoft** [comment]
I tried editing the json to add @ class to the jsog ref elements, but this had no effect.

It appears that JSOGDeserializer should be implementing `com.fasterxml.jackson.databind.JsonDeserializer#deserializeWithType(com.fasterxml.jackson.core.JsonParser, com.fasterxml.jackson.databind.DeserializationContext, com.fasterxml.jackson.databind.jsontype.TypeDeserializer)`

So that when de-serializing with a type, it can "do the right thing". As it stands in this case `com.voodoodyne.jackson.jsog.JSOGRefDeserializer#deserialize` never gets called, so of course jackson doesn't know what to do with the JSOGRef... boom

**Comment by nsoft** [comment]
Someone with sufficient karma should change the title of this to "InvalidTypeIdException when default serialization is enabled"
